### PR TITLE
add in ps and source read log variables

### PR DESCRIPTION
**Pull request by teknogeek0**
We've been running into an issue where we are generating so much log content from a single Heroku app that its overwhelming the plugin over time ( at least that appears to be whats happening). We have ~ a dozen processes in each of our Heroku apps, over a hundred dynos, and so by tailing the logs just for certain processes/sources we can spread it out across multiple instances running Logstash.

How does this change the plugin config? As an example:

```
input {
 heroku {
   app => "my-app"
   ps => "my-ps"
   source => "heroku" (or app)
   type => "my-app_my-ps"
 }
}
```

As you can see from the commit, this also adds in the heroku_ps and heroku_source fields to the message.

I've tested this plugin in Logstash 1.4.2, using the latest Heroku gem.

### CODE REVIEW

**Comment by teknogeek0** [comment]
Just wanted to update to say that I have signed Elastic's CLA.

**Comment by teknogeek0** [comment]
bump.

Any thoughts?

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by vincent144** [comment]
jenkins, test it

**Pull request closed without merging**
