### PR TITLE
fix heroku dependency

### LINKED ISSUE #4: Uninitialized constant Heroku::Client
Hello I’m trying to run logstash with heroic input, but it doesn’t work. 
I tried everything and all the time I get error:

```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Heroku app=>”my-app">
  Error: uninitialized constant Heroku::Client
  Exception: NameError
  Stack: org/jruby/RubyModule.java:2726:in `const_missing'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-heroku-0.1.4/lib/logstash/inputs/heroku.rb:36:in `run'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"182", :method=>"inputworker"}
org/jruby/RubyModule.java:2726:in `const_missing'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-heroku-0.1.4/lib/logstash/inputs/heroku.rb:36:in `run'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'
/home/vagrant/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input’
```

I’m logged in on heroku, I have java 8, I tried java 7 but the same error.

### PR DESCRIPTION
**Pull request by carchrae**
i've signed the CLA, so please merge this trivial fix.  

fixes logstash-plugins/logstash-input-heroku#4

### CODE REVIEW

**Comment by karmi** [comment]
Hi @carchrae, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-heroku/pull/10.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jordansissel** [comment]
3 commits for one line change, weird! I'll squash this before merging.

**Comment by carchrae** [comment]
yeah, sorry.  i had to re-do the commit with me as the cla enabled user.

**Comment by skijash** [comment]
Hey guys, when do you think this will go into a release? I'm having those "Error: uninitialized constant Heroku::Client" issues, and can't pull from heroku.

**Comment by carchrae** [comment]
@skijash - i never got this plugin to work properly even after this fix (hit something else).  i ended up using the logstash HTTP logger and just posting payloads to logstash via POST calls.

**Comment by skijash** [comment]
@carchrae Can you please email me the setup you used? You can find my address on my profile. Thanks!

**Comment by carchrae** [comment]
no need to email: https://www.elastic.co/blog/introducing-logstash-input-http-plugin

**Pull request merged**
